---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: workstation-os
# description will be included in the image's metadata
description: My custom workstation OS setup based on Universal Blue with Hyprland
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 43

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* into your image's root folder /

  - type: dnf
    repos:
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
      nonfree: rpmfusion
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
      copr:
        - atim/starship
        - sdegler/hyprland
        - errornointernet/walker
        - wezfurlong/wezterm-nightly
        - zeno/scrcpy
        - erikreider/SwayNotificationCenter
        - g3tchoo/prismlauncher
    install:
      skip-unavailable: true
      install-weak-deps: false
      packages:
        # Core utilities
        - git
        - git-lfs
        - glibc
        - curl
        - xxd
        - htop
        - nano
        - neovim
        - code
        - https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
        - zed

        # Shell
        - zsh
        - starship

        # Media
        - vlc
        - mpv

        # Hyprland and Wayland tools
        - hyprland
        - uwsm
        - sddm
        - waybar
        - rofi
        - walker
        - gtk4-layer-shell
        - elephant
        - swww
        - swaync
        - wezterm
        # System utilities
        - kvantum
        - gtk-murrine-engine
        - libadwaita
        - libadwaita-devel
        - qt5ct
        - qt6ct
        - engrampa
        - atril
        - eom
        - pluma
        - mate-calc
        - pipewire
        - wireplumber
        - pipewire-pulseaudio
        - pavucontrol
        - network-manager-applet
        - distrobox
        - nwg-look
        - xfce4-power-manager
        - nemo
        - simple-scan
        - blueman
        # Themes and fonts
        - papirus-icon-theme
        - gnome-themes-extra
        - kf6-kirigami
        - plasma5support
        - plasma-workspace
        - mate-system-monitor
        - sassc
        - jetbrains-mono-fonts-all
        - google-noto-emoji-fonts
        - adwaita-fonts-all

        # Applications
        - prismlauncher

  - type: script
    scripts:
      - install-gtk-theme.sh
      #- install-icon-theme.sh
      - install-kv-sddm-theme.sh

  - type: fonts
    fonts:
      google-fonts:
        - Roboto
        - Inter
        - NotoEmoji
      nerd-fonts:
        - JetBrainsMono

  - type: systemd
    system:
      enabled:
        - podman.socket
        - sddm.service

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - com.discordapp.Discord
          - com.bitwarden.desktop
          - md.obsidian.Obsidian
          - com.valvesoftware.Steam
          - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
          - org.chromium.Chromium
          - com.brave.Browser

  - type: signing
  - type: chezmoi
    repository: "https://github.com/TheFocusDevHUN/dotfiles"
    all-users: true
    file-conflict-policy: skip
