---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: workstation-os-tfd
# description will be included in the image's metadata
description: My custom workstation OS setup based on Universal Blue with Hyprland
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 42

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-42/atim-starship-fedora-42.repo
      - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-42/erikreider-SwayNotificationCenter-fedora-42.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-42/solopasha-hyprland-fedora-42.repo
      - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-42/wezfurlong-wezterm-nightly-fedora-42.repo
      - https://copr.fedorainfracloud.org/coprs/zeno/scrcpy/repo/fedora-42/zeno-scrcpy-fedora-42.repo
      - https://copr.fedorainfracloud.org/coprs/g3tchoo/prismlauncher/repo/fedora-42/g3tchoo-prismlauncher-fedora-42.repo
      - https://copr.fedorainfracloud.org/coprs/markupstart/SwayOSD/repo/fedora-42/markupstart-SwayOSD-fedora-42.repo
      - https://copr.fedorainfracloud.org/coprs/lihaohong/scc/repo/fedora-42/lihaohong-scc-fedora-42.repo
    install:
      # Core utilities
      - git
      - git-lfs
      - glibc
      - scc
      - curl
      - xxd
      - htop
      - nano
      - neovim

      # Shell
      - zsh
      - starship

      # Media
      - vlc
      - mpv

      # Hyprland and Wayland tools
      - hyprland
      - waybar
      - rofi
      - swww
      - swaync
      - wezterm

      # System utilities
      - pipewire
      - wireplumber
      - pipewire-pulseaudio
      - pavucontrol
      - network-manager-applet
      - distrobox
      - nwg-look
      - xfce4-power-manager
      - nemo
      - blueman

      # Themes and fonts
      - adw-gtk3-theme
      - adwaita-icon-theme
      - jetbrains-mono-fonts-all
      - google-noto-emoji-fonts
      - adwaita-fonts-all

      # Applications
      - prismlauncher

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: akmods
    base: main
    install:
      - v4l2loopback

  - type: systemd
    system:
      enabled:
        - podman.socket

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - com.discordapp.Discord
          - com.bitwarden.desktop
          - md.obsidian.Obsidian
          - com.valvesoftware.Steam
          - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
          - org.chromium.Chromium
          - com.brave.Browser

  - type: signing
  - type: chezmoi
    repository: "https://github.com/TheFocusDevHUN/dotfiles" # my dotfiles repo
    all-users: true # make users have to enable chezmoi manually
    file-conflict-policy: skip # override changed files with those from the repo
