---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: workstation-os
# description will be included in the image's metadata
description: My custom workstation OS setup based on Universal Blue with Hyprland
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 43

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* into your image's root folder /

  - type: dnf
    repos:
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
      nonfree: rpmfusion
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
      copr:
        - atim/starship
        - sdegler/hyprland
        - wezfurlong/wezterm-nightly
        - zeno/scrcpy
        - erikreider/SwayNotificationCenter
        - g3tchoo/prismlauncher
    install:
      skip-unavailable: true
      packages:
        # Core utilities
        - git
        - git-lfs
        - glibc
        - curl
        - xxd
        - htop
        - nano
        - neovim
        - code
        - zed

        # Shell
        - zsh
        - starship

        # Media
        - vlc
        - mpv

        # Hyprland and Wayland tools
        - hyprland
        - uwsm
        - greetd
        - waybar
        - rofi
        - swww
        - swaync
        - wezterm
        # System utilities
        - kvantum
        - pipewire
        - wireplumber
        - pipewire-pulseaudio
        - pavucontrol
        - network-manager-applet
        - distrobox
        - nwg-look
        - xfce4-power-manager
        - nemo
        - blueman
        # Themes and fonts
        - materia-gtk-theme
        - materia-kde-kvantum
        - papirus-icon-theme
        - jetbrains-mono-fonts-all
        - google-noto-emoji-fonts
        - adwaita-fonts-all

        # Applications
        - prismlauncher

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: systemd
    system:
      enabled:
        - podman.socket
        - greetd.service

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - com.discordapp.Discord
          - com.bitwarden.desktop
          - md.obsidian.Obsidian
          - com.valvesoftware.Steam
          - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
          - org.chromium.Chromium
          - com.brave.Browser

  - type: signing
  - type: chezmoi
    repository: "https://github.com/TheFocusDevHUN/dotfiles"
    all-users: true
    file-conflict-policy: skip
