[Autologin]
# Whether sddm should automatically log back into sessions when they exit
#Relogin=false

# Name of session file for autologin session
#Session=

# Username for autologin session
#User=

[General]
# Enable Qt's automatic high-DPI scaling
EnableHiDPI=false

# Control x11/wayland startup
DisplayServer=wayland

[Theme]
# Current theme name
Current=Colloid-dark

# Enable display of custom user avatars
EnableAvatars=true

# Theme directory path
#ThemeDir=/usr/share/sddm/themes

# Maximum user id for displayed users
#MaximumUid=60000

# Minimum user id for displayed users
#MinimumUid=1000

# Remember the session of the last successfully logged in user
RememberLastSession=true

# Remember the last successfully logged in user
RememberLastUser=true
